DjangoDemo06/DjangoDemo06/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('index.urls')),
]

DjangoDemo06/index/urls.py
from django.conf.urls import url
from .views import *
urlpatterns = [
  url(r'^01-request/$',request_views),
  url(r'^02-request/$',request02_views),
  url(r'^03-post/$',post_views),
  url(r'^04-all/$',all_views),
  url(r'^05-register/$',register_views),
  url(r'^06-form/$',form_views),
]

urlpatterns += [
  url(r'^07-form-register/$',form_register),
  url(r'^08-widget1/$',widget1_views),
  url(r'^09-widget2/$',widget2_views),
  url(r'^10-setCookie/$',setcookie_views),
  url(r'^11-getCookie/$',getcookie_views),
]

urlpatterns += [
  url(r'^12-ajax/$',ajax_views),
  url(r'^12-server/$',server12_views),
  url(r'^13-ajax-post/$',ajax_post),
  url(r'^13-server/$',server13_views),
]

DjangoDemo06/index/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
  name = models.CharField(max_length=30)
  age = models.IntegerField()
  email = models.EmailField()
  isActive = models.BooleanField(default=True)

  def to_dict(self):
    dic = {
      'id':self.id,
      'name':self.name,
      'age':self.age,
      'email':self.email,
      'isActive':self.isActive,
    }
    return dic

  class Meta:
    db_table = 'author'

DjangoDemo06/index/forms.py
from django import forms

#声明ChoiceField要用到的数据
from index.models import Author

TOPIC_CHOICE = (
  ('1','好评'),
  ('2','中评'),
  ('3','差评'),
)

#表示评论内容的表单控件的class
#控件1-评论标题-文本框
#控件2-电子邮箱-邮件框
#控件3-评论内容-Textarea
#控件4-评论级别-下拉选择框
#控件5-是否保存-复选框
class RemarkForm(forms.Form):
  #评论标题
  # forms.CharField() - 文本框
  # label : 控件前的文本标签
  subject = forms.CharField(label='标题')
  #电子邮箱
  # forms.EmailField() - Email框
  # label : 控件前的文本标签
  email = forms.EmailField(label='邮箱')
  #品论内容
  # widget=Textarea : 将当前的单行文本框变为多行文本域
  message = forms.CharField(label='内容',widget=forms.Textarea)
  #品论级别
  # forms.ChoiceField() - 下拉列表框
  # choices : 表示当前下拉列表框中的数据,取值为元组或列表
  topic = forms.ChoiceField(label='级别',choices=TOPIC_CHOICE)
  #是否保存-复选框
  isSaved = forms.BooleanField(label='是否保存')

# class RegisterForm(forms.Form):
#   name = forms.CharField(label='姓名')
#   age = forms.IntegerField(label='年龄')
#   email = forms.EmailField(label='邮箱')

# 将Models 和 Forms 结合到一起
class RegisterForm(forms.ModelForm):
  class Meta:
    #1.指定关联的Model
    model = Author
    #2.指定生成控件的字段们
    # fields = "__all__"
    fields = ['name','age','email']
    #3.指定每个控件对应的label
    labels = {
      'name':'用户名称',
      'age':'用户年龄',
      'email':'用户邮箱',
    }

class WidgetForm1(forms.Form):
  #通过小部件的方式，为uname绑定html属性
  uname = forms.CharField(
    label='用户名称',
    widget=forms.TextInput(
      attrs = {
        'class':'form-control',
        'placeholder':'请输入用户名称'
      }
    )
  )
  #通过小部件,将upwd指定为密码框
  upwd = forms.CharField(
    label='用户密码',
    widget=forms.PasswordInput(
      attrs = {
        'class':'form-control',
        'placeholder':'请输入密码',
      }
    )
  )

class WidgetForm2(forms.ModelForm):
  class Meta:
    #指定关联的实体
    model = Author
    #指定要显示的字段
    fields = ['name','age','email']
    #指定字段对应的标签
    labels = {
      'name':'用户姓名',
      'age':'用户年龄',
      'email':'用户邮箱',
    }
    #指定字段对应的小部件
    widgets = {
      'age':forms.NumberInput(
        attrs = {
          'placeholder':'请输入年龄',
          'class':'form-control',
        }
      ),
      'email':forms.EmailInput(
        attrs = {
          'placeholder':'请输入您的电子邮箱',
          'class':'form-control',
        }
      )
    }

DjangoDemo06/index/views.py
import json

from django.core import serializers
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
from index.forms import *
from index.models import Author


def request_views(request):
  scheme = request.scheme
  body = request.body
  path = request.path
  full_path = request.get_full_path()
  host = request.get_host()
  method = request.method
  post = request.POST
  get = request.GET
  cookies = request.COOKIES
  meta = request.META
  return render(request,'01-request.html',locals())

def request02_views(request):
  year = request.GET.get('year','1900')
  month = request.GET.get('month','01')
  day = request.GET.get('day','01')
  print("传递的数据:%s年%s月%s日" % (year,month,day))
  return HttpResponse('Get OK')

def post_views(request):
  if request.method == 'GET':
    return render(request,'03-post.html')
  else:
    uname = request.POST.get('uname')
    upwd = request.POST.get('upwd')
    return HttpResponse("用户名:%s,用户密码:%s" % (uname,upwd))

def all_views(request):
  authors = Author.objects.all()
  for au in authors:
    print(au.id,au.name,au.age,au.email)
  return HttpResponse("Query OK")

def register_views(request):
  if request.method == 'GET':
    return render(request,'05-register.html')
  else:
    #接收前端传递过来的数据
    name = request.POST.get('name')
    age = request.POST.get('age')
    email = request.POST.get('email')
    #将数据封装成 author 的对象
    au = Author()
    au.name = name
    au.age = age
    au.email = email
    #调用author的save()将数据保存进数据库
    au.save()
    return HttpResponse("Register OK")

def form_views(request):
  if request.method == 'GET':
    #创建RemarkForm的对象,并发送到06-form.html中
    form = RemarkForm()
    return render(request,'06-form.html',locals())
  else:
    # subject = request.POST.get('subject')
    # email = request.POST.get('email')
    # message = request.POST.get('message')
    # topic = request.POST.get('topic')
    # isSaved = request.POST.get('isSaved','0')

    #使用forms的对象来接收提交的数据
    #1.将request.POST的数据提交给RemarkForm
    form = RemarkForm(request.POST)
    #2.让RemarkForm的对象通过验证
    if form.is_valid():
      #3.通过验证后再获取各个控件的值
      cd = form.cleaned_data
      print(cd['email'],cd['subject'])

      return HttpResponse("Post OK")
      # return HttpResponse("Subject:%s,Email:%s,Message:%s,Topic:%s,IsSaved:%s" % (subject,email,message,topic,isSaved))

def form_register(request):
  if request.method == 'GET':
    form = RegisterForm()
    return render(request,'07-form-register.html',locals())
  else:
    # 将request.POST中的数据提交给RegisterForm()
    form = RegisterForm(request.POST)
    # 将数据通过验证
    if form.is_valid():
      # 验证过后获取数据并保存进数据库
      au = Author(**form.cleaned_data)
      au.save()
      return HttpResponse("Register OK")

def widget1_views(request):
  if request.method == 'GET':
    form = WidgetForm1()
    return render(request,'08-widget1.html',locals())

def widget2_views(request):
  if request.method == 'GET':
    form = WidgetForm2()
    return render(request,'08-widget1.html',locals())

def setcookie_views(request):
  resp = HttpResponse('添加Cookie成功')
  #保存cookie的值到resp中
  resp.set_cookie('test_name','wangwc',60*60*24*365)
  return resp

def getcookie_views(request):
  if 'test_name' in request.COOKIES:
    value = request.COOKIES.get('test_name')
    return HttpResponse("test_name的值为:"+value)
  else:
    return HttpResponse('cookie中没有您要找的值')

def ajax_views(request):
  return render(request,'12-ajax.html')

def server12_views(request):
  # list = ["NARUTO","HINATA","SAKURA","SASUKE"]
  # jsonStr = json.dumps(list)

  #查询Author中所有的数据
  # authors=Author.objects.all()
  #将authors转换为json格式的字符串
  # jsonStr=serializers.serialize('json',authors)
  # print(jsonStr)

  #查询id为2的Author的数据
  # author=Author.objects.get(id=2)
  # 以下写法错误:serialize()只能将查询结果集转换成json,单个对象则不可以
  # jsonStr=serializers.serialize('json',author)

  # 以下方式写法正确
  # authors = Author.objects.filter(id=2)
  # jsonStr=serializers.serialize('json',authors)

  author=Author.objects.get(id=2)
  jsonStr=json.dumps(author.to_dict())
  return HttpResponse(jsonStr)

def ajax_post(request):
  return render(request,'13-post.html')

def server13_views(request):
  uname = request.POST['uname']
  uage = request.POST['uage']
  return HttpResponse("uname:%s,uage:%s" % (uname,uage))

DjangoDemo06/templates/01-request.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
  <a href="/01-request/">跳转至01-request</a>
  <h3>scheme:{{ scheme }}</h3>
  <h3>body:{{ body }}</h3>
  <h3>path:{{ path }}</h3>
  <h3>full_path:{{ full_path }}</h3>
  <h3>host:{{ host }}</h3>
  <h3>method:{{ method }}</h3>
  <h3>get:{{ get }}</h3>
  <h3>post:{{ post }}</h3>
  <h3>cookies:{{ cookies }}</h3>
  <h3>meta:{{ meta }}</h3>
</body>
</html>

DjangoDemo06/templates/03-post.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<form action="/03-post/" method="post">
  <!-- csrf_token 表示要提交给服务器的一个口令 -->
  {% csrf_token %}
  <p>
    用户名称: <input type="text" name="uname">
  </p>
  <p>
    用户密码: <input type="password" name="upwd">
  </p>
  <p>
    <input type="submit">
  </p>
</form>
</body>
</html>

DjangoDemo06/templates/05-register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<form action="/05-register/" method="post">
  {% csrf_token %}
  <p>
    姓名: <input type="text" name="name">
  </p>
  <p>
    年龄: <input type="number" name="age">
  </p>
  <p>
    邮箱: <input type="email" name="email">
  </p>
  <p>
    <input type="submit">
  </p>
</form>
</body>
</html>

DjangoDemo06/templates/06-form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <style>
    #id_subject{
      border:none;
      border-bottom:1px solid #000;
      outline:none;
    }
  </style>
</head>
<body>
{% comment '手动解析' %}
<form action="/06-form/" method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label }}:{{ field }}
    </p>
  {% endfor %}
  <p>
    <input type="submit">
  </p>
</form>
{% endcomment %}

{% comment '自动解析- {{ form.as_p }}' %}
<form action="/06-form/" method="post">
  {{ form.as_p }}
  <p>
    <input type="submit">
  </p>
</form>
{% endcomment %}

{% comment '自动解析- {{ form.as_ul }}' %}
<form action="/06-form/" method="post">
  <ol>
    {{ form.as_ul }}
    <li>
      <input type="submit">
    </li>
  </ol>
</form>
{% endcomment %}

<form action="/06-form/" method="post">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
    <tr>
      <td colspan="2">
        <input type="submit">
      </td>
    </tr>
  </table>
</form>
</body>
</html>

DjangoDemo06/templates/07-form-register.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<form action="/07-form-register/" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <p>
    <input type="submit">
  </p>
</form>
</body>
</html>

DjangoDemo06/templates/08-widget1.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <style>
    input.form-control{
      border:1px solid #000;
      width:300px;
      height:30px;
      box-sizing:border-box;
      padding:3px 10px;
      outline:none;
    }
  </style>
</head>
<body>
<form action="">
  {{ form.as_p }}
</form>
</body>
</html>

DjangoDemo06/templates/12-ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <script src="/static/jquery-1.11.3.js"></script>
  <script>
    function btnAjax(){
      $.get('/12-server/',function(data){
        /**循环遍历后端响应回来的列表数据*/
        /*
        $.each(data,function(i,obj){
          console.log("===============");
          console.log("ID:"+obj.pk);
          console.log("Name:"+obj.fields.name);
          console.log("Age:"+obj.fields.age);
          console.log("Email:"+obj.fields.email);
          console.log("IsActive:"+obj.fields.isActive);
        })
        */

        console.log(data);

      },'json');
    }
  </script>
</head>
<body>
  <button onclick="btnAjax()">ajax请求</button>
</body>
</html>

DjangoDemo06/templates/13-post.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <script src="/static/jquery-1.11.3.js"></script>
  <script>
    function btnPost(){
      $.post('/13-server/',{
        'uname':'MrWang',
        'uage':30,
        'csrfmiddlewaretoken':$("[name='csrfmiddlewaretoken']").val()
      },function(data){
        console.log(data);
      });
    }
  </script>
</head>
<body>
  <button onclick="btnPost()">AJAX-POST</button>
  {% csrf_token %}
</body>
</html>